version: '3.8'
services:
  budgetbuddy-backend:
    build: ./backend
    ports:
      - "8080:8000"
    command: uvicorn main:app --host 0.0.0.0 --reload

  budgetbuddy-frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=budgetbuddy-db
