version: '3.8'
services:
  budgetbuddy-backend:
    build: ./backend
    ports:
      - "8080:8000"
    command: uvicorn main:app --host 0.0.0.0 --reload

  budgetbuddy-frontend:
    build: 
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - "80:80"